resolver: lts-20.24
packages:
- '.'
extra-deps:
  - xmobar-0.44.2
flags: {}
# flags:
#   xmobar:
#     with_xft: true
extra-package-dbs: []
nix:
  packages:
    - pkg-config
    - autoconf
    - gcc
    - gmp
    - xorg.libX11
    - xorg.libXext
    - xorg.libXft
    - xorg.libXinerama
    - xorg.libXpm
    - xorg.libXrandr
    - xorg.libXrender
    - xorg.libXScrnSaver
